OCSSW server module throws java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException  in Java 9 or higher. The reason was that the JAXB APIs are considered to be Java EE APIs, and therefore are no longer contained on the default class path in Java SE 9. In Java 11 they are completely removed from the JDK. This problem is resolved by adding the JAX-B APIs as a maven dependency.